### ISSUE TITLE
Choose technology for adding comments to students. 

### ISSUE THREAD

**Issue by damorim** [damorimRG/practical_testing_book#4]
Check gerrit! 

Please, consider that I need to comment contributions of about ~30 students. For example, discussing individual PRs would not be practical for me, for example.

**Comment by rafaelmotaalves** [comment]
@damorim , Gerrit works like the Github PR Review tool, so it probably won't work for you.

About the tool for adding comments to the Live web page, I only found this tool that worked well for the purpose: https://usepastel.com/, but it won't work for us because, for the free version, the comments are deleted within 3 days.

My suggestion is to use the special tag for markdown to signal observations, could be something like:
> **TODO**: Please explain this topic x better - 14/07/200

the markup to create the notation above is:

`> **TODO**: Please explain this topic x better - 14/07/200`

I also suggest, that every time you add a batch of comments, post a message on google.classroom so that all students are notified.

**Comment by damorim** [comment]
On Tue, Jul 14, 2020 at 4:46 PM Rafael Mota Alves <notifications@github.com>
wrote:

> @damorim <https://github.com/damorim> , Gerrit works like the Github PR
> Review tool, so it probably won't work for you.
>
> About the tool for adding comments to the Live web page, I only found this
> tool that worked well for the purpose: https://usepastel.com/, but it
> won't work for us because, for the free version, the comments are deleted
> within 3 days.
>
> My suggestion is to use the special tag for markdown to signal
> observations, could be something like:
>
> *TODO*: Please explain this topic x better - 14/07/200
>
> the markup to create the notation above is:
>
> > **TODO**: Please explain this topic x better - 14/07/200
>

Obrigado! Vou usar isto.


> I also suggest, that every time you add a batch of comments, post a
> message on google.classroom so that all students are notified.
>

Acho que isto é inviável.
